### PR TITLE
Re-implement Dotclear importer

### LINKED ISSUE #510: No dotclear command in jekyll/commands/import.rb
Sorry if this is plain silly, I was trying to use "jekyll import" (bundle-updated) to import my dotclear blog, as documented in https://import.jekyllrb.com/docs/dotclear/ and I get 

`jekyll 4.3.2 | Error:  Whoops, we can't understand your command.
jekyll 4.3.2 | Error:  invalid option: --datafile
jekyll 4.3.2 | Error:  Run your command again with the --help switch to see available options.
/home/jr/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:33:in `go': invalid option: --datafile (OptionParser::InvalidOption)
`

"jekyll import --help" doesn't help. Tried to find out what's the matter, and I found a jekyll/commands/import.rb file that included all the importers but dotclear.  Is it an oversight or has it been removed as obsolete?

### PR DESCRIPTION
**Pull request by ashmaroli**
Re-implement Dotclear importer based on export file provided by @jrfern in https://github.com/jekyll/jekyll-import/issues/510#issuecomment-1453747018.

This drops dependency on `activesupport`, includes associated tests and adds provided export file for future development.

Closes #510

### CODE REVIEW

**Comment by ashmaroli** [comment]
Hello @jrfern,
The Dotclear importer has been rewritten based the export file you had provided.
I would now like to know the directory structure of the "media folder" (`media.zip` unpacked) so as to implement the functionality behind `--mediafolder` and maintain backwards-compatibility.

If you wish to try this out, you may edit your Gemfile as follows:
```ruby
# Gemfile

gem "jekyll"
gem "jekyll-import", github: "jekyll/jekyll-import", ref: "refs/pull/512/head"
```
(There is no need to include `activesupport` or any of the previous dependency gems).

---

TODO:
  - Implement `--mediafolder`
  - Document that the imported posts are in `_drafts` to avoid unintentional overwriting of existing namesake in `_posts`.
  - Document that comments received for the imported posts will not be imported from the export file.

**Comment by jrfern** [comment]
Great! Thank you very much. Now I get 
```
invalid option: --mediafolder (OptionParser::InvalidOption)
```
When run without this option (and after following your instructions)
```
$ bundle exec jekyll import dotclear --datafile path_to_backup.txt
jekyll 4.3.2 | Error:  Illegal quoting in line 1.
/usr/lib/ruby/3.1.0/csv/parser.rb:955:in `parse_quotable_robust': Illegal quoting in line 1. (CSV::MalformedCSVError)
```

> I would now like to know the directory structure of the "media folder" (media.zip unpacked) 

Inside the zip archive there's a "img" directory with the image files and subdirectories.

File: lib/jekyll-import/importers/dotclear.rb [hunk 1]
```diff
@@ -1,121 +1,101 @@
...
 
-          if line.start_with?("[") # post | media \ meta | comment...
-            type_data = line.split(" ").first[1..-1]
-            headers[type_data] = extract_headers_section(line)
-            next
+        # rubocop:disable Style/IfUnlessModifier
+        def validate(opts)
+          file_path = opts["datafile"]
+          if file_path.nil? || file_path.empty?
+            Jekyll.logger.abort_with "Import Error:", "Dotclear export file not found!"
```
Comment (parkr) [inline lib/jekyll-import/importers/dotclear.rb:23]: Should we be clear that this comes from the "datafile" option?

File: lib/jekyll-import/importers/dotclear.rb [hunk 2]
```diff
@@ -1,121 +1,101 @@
...
+              "lang"   => post["post_lang"],
+              "tags"   => tags[post["post_id"]],
+            }.tap(&:compact!)
+
+            # keep a record of existing URL for the post. Jekyll may or may not generate the same
+            # URL depending on `permalink` settings in Jekyll configuration.
+            front_matter_data["dotclear_post_url"] = post["post_url"]
+
+            Jekyll.logger.info "Creating:", path
+            File.write(path, "#{YAML.dump(front_matter_data)}---\n\n#{ReverseMarkdown.convert(content).strip}\n")
```
Comment (parkr) [inline lib/jekyll-import/importers/dotclear.rb:58]: ReverseMarkdown-- should this be an optional thing? Or do we always want to reverse it?

File: lib/jekyll-import/importers/dotclear.rb [hunk 3]
```diff
@@ -1,121 +1,101 @@
...
+        # rubocop:enable Style/IfUnlessModifier
+
+        def process(_opts)
+          Jekyll.logger.info "Importing.."
+          tags = register_post_tags
+          posts = @data["post"]
+          FileUtils.mkdir_p("_drafts") unless posts.empty?
+
+          posts.each do |post|
+            date, title, content = post.values_at("post_creadt", "post_title", "post_content")
```
Comment (parkr) [inline lib/jekyll-import/importers/dotclear.rb:43]: `post_created`? Might have forgotten an e?

File: lib/jekyll-import/importers/dotclear.rb [hunk 4]
```diff
@@ -1,121 +1,101 @@
...
+              "layout" => "post",
+              "title"  => title,
+              "date"   => date,
+              "lang"   => post["post_lang"],
+              "tags"   => tags[post["post_id"]],
+            }.tap(&:compact!)
+
+            # keep a record of existing URL for the post. Jekyll may or may not generate the same
+            # URL depending on `permalink` settings in Jekyll configuration.
+            front_matter_data["dotclear_post_url"] = post["post_url"]
```
Comment (parkr) [inline lib/jekyll-import/importers/dotclear.rb:55]: Could this be unlined into the creation of front_matter_data instead of getting its own declaration? Or are we worried it'll be null?

File: test/test_dotclear_importer.rb [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+
+        assert_includes output, error_msg
+      end 
+    end
+  end
+
+  context "Importing with valid export file" do
+    setup do
+      orig_pwd = Dir.pwd
+      @export_file = File.join(orig_pwd, "test/mocks/dotclear.txt")
```
Comment (parkr) [inline test/test_dotclear_importer.rb:39]: If this variable is not used outside the setup method then we don't need it to be an instance variable.

**Review by parkr — APPROVED** [review]

File: lib/jekyll-import/importers/dotclear.rb (hunk 3 above)
Comment (ashmaroli) [reply lib/jekyll-import/importers/dotclear.rb:43]: The strings here mirror the header keys in the backup file (attached as part of this PR):
```
[post post_id,blog_id,user_id,cat_id,post_dt,post_tz,post_creadt,post_upddt,post_password,...]
```

File: lib/jekyll-import/importers/dotclear.rb (hunk 4 above)
Comment (ashmaroli) [reply lib/jekyll-import/importers/dotclear.rb:55]: No, we are not worried about this being null since we are calling `compact!` on the hash. This is given a separate declaration to have the comment above it, as to shed light on why we are not setting this as value to a `permalink` front matter key right away.

File: test/test_dotclear_importer.rb (hunk 5 above)
Comment (ashmaroli) [reply test/test_dotclear_importer.rb:39]: This variable is subsequently used to assert expected log message.

**Comment by ashmaroli** [comment]
@jrfern The `CSV::MalformedCSVError` is a bug that needs to be fixed. I would like to take a look at the actual backup file you used to test this branch. You may email the file to me directly instead of exposing it here.

> I would now like to know the directory structure of the "media folder" (media.zip unpacked)
>
> > Inside the zip archive there's a "img" directory with the image files and subdirectories.

In the backup file you provided previously, the value to key `media.media_file` is `"MiUser/250px-MonaLisaGraffiti.JPG"`. So, is the "img" dir parent directory to "MiUser`?

File: lib/jekyll-import/importers/dotclear.rb (hunk 2 above)
Comment (ashmaroli) [reply lib/jekyll-import/importers/dotclear.rb:58]: The current implementation on this branch creates `.md` files, so reversing the (X)HTML to Markdown felt necessary.

Do you think it's best to create `.html` files with markup as in the backup file?

File: lib/jekyll-import/importers/dotclear.rb (hunk 1 above)
Comment (ashmaroli) [reply lib/jekyll-import/importers/dotclear.rb:23]: That sounds better! 👍

**Comment by jrfern** [comment]
> @jrfern The `CSV::MalformedCSVError` is a bug that needs to be fixed.

Yes, please, @ashmaroli 

>  I would like to take a look at the actual backup file you used to test this branch. You may email the file to me directly instead of exposing it here. (email address is attached to all of my commits on GitHub)

ashmaroli at users.noreply.github.com? Impossible. I'm feeling silly, but I haven't been able to find your email, just your jekyll-talk, github, reddit, linkedin accounts... Mine is jrfern at gmail...

> > I would now like to know the directory structure of the "media folder" (media.zip unpacked)
> In the backup file you provided previously, the value to key `media.media_file` is `"MiUser/250px-MonaLisaGraffiti.JPG"`. So, is the "img" dir parent directory to "MiUser`?

I don't understand, the MiUser phrase was a reference to the path. I unzipped the media.zip file, and it created media/img/image_files. Then run the command with  --mediafolder path/media/img/ (as it never worked I don't know if it should be simply --mediafolder path/media/ ).

Hope this helps. One more thing, for my tests your suggested 
```
gem "jekyll-import", github: "jekyll/jekyll-import", ref: "refs/pull/512/head
```
Should I change that now that the PR has been approved?

**Comment by ashmaroli** [comment]
> I'm feeling silly, but I haven't been able to find your email..

Ah! I should have just mentioned it right away instead.. it's ashmaroli at gmail..

> run the command with --mediafolder path/media/img/ (as it never worked I don't know if it should be simply --mediafolder path/media/ )...

The original implementation (in existing releases) was to expect just `path/media/`. The importer would then copy the contents into destination path `assets/images/`. For example, say I provide `--mediafolder media`. Then the importer would look for `media/MiUser/250px-MonaLisaGraffiti.JPG` and if found, copy to `assets/images/MiUser/250-px....JPG`.
The proposed implementation in this branch hasn't actually exposed the `--mediafolder` yet. (So, it will always fail if you try). But it will eventually have similar behavior to maintain backwards-compatibility.

> Should I change that now that the PR has been approved?

The reference is permanent. It would be valid even if the pull request branch gets deleted after the pull request is merged. However, since the pull request is still a work-in-progress, you may have to run `bundle update jekyll-import` to get the latest state of this branch. (You don't have to update until I ask you for feedback.)

**Comment by jrfern** [comment]
@ashmaroli Real backup file sent privately.
I'm learning so much - thank you again.

**Comment by ashmaroli** [comment]
Thanks @jrfern
Received the backup file. Will use it to make changes to this branch.

**Comment by ashmaroli** [comment]
Hello @jrfern
You may update your bundle reference to this branch by running `bundle update jekyll-import` to test at your end.
I have also updated the importer documentation for better understanding. You may preview the [document here](https://deploy-preview-512--jekyll-import.netlify.app/docs/dotclear/).

**Comment by jrfern** [comment]
Recuperated 60 entries into _drafts and their images! Great! I'm fighting at the moment with the paginate-v2 plugin and so can't check but I would say that the import worked.

Thank you again, @ashmaroli

**Comment by ashmaroli** [comment]
Happy to hear that, @jrfern. Good luck tackling the pagination plugin 🙂
Thank you for testing and giving feedback.

**Comment by jrfern** [comment]
First analysis of the new plugin. I moved the older post ('Informe K-12 Open Minds Conference 2007 - parte I: Europeos') to the posts directory. 

Works quite well, not totally well.

## The excerpt part is missing (it's in the backup). For example:
```
"Informe K-12 Open Minds Conference 2007 - parte I: Europeos","<blockquote>\r\n<p><em>I was invited to&nbsp; attend the Conference held in Indianapolis. It was the start of something, I have to say. This is part one of my report in Spanish.</em></p>\r\n\r\n<p>La ventaja de dar tiempo a las cosas para ...
...
... y perfilar matices.</p>\r\n</blockquote>\r\n\r\n<p> </p>","<p style=\"text-align: justify;\">Escribo un informe sobre la K-12 Open Minds Conference....
```
This is converted into
```
<p style="text-align: justify;">Escribo un informe sobre la K-12 Open Minds Conference. Si eres impaciente puedes leer ya mucha información sobre lo que allí se habló en el <a href="http://k12openminds.wikispaces.com/" hreflang="es">K-12 Open Minds Conference Resource Site</a>.</p>
```

The blockquote (the whole header)  is missing in the import.

## ERROR `/assets/dotclear/img/.dia_1_m.jpg' not found.

In the backup
```
<p style=\"text-align: justify;\"><a class=\"media-link\" href=\"/dotclear/public/img/dia_1.jpg\"><img alt=\"\" class=\"media\" src=\"/dotclear/public/img/.dia_1_m.jpg\" style=\"float: left; margin: 0 1em 1em 0;\" /></a>
```
Now it is
```
<p style="text-align: justify;"><a class="media-link" href="/assets/dotclear/img/dia_1.jpg"><img alt="" class="media" src="/assets/dotclear/img/.dia_1_m.jpg" style="float: left; margin: 0 1em 1em 0;" /></a>
```

The images are treated as links. That was OK in the sense that there used to be two versions of each image, and the small one is a link to the big one, but there are no names starting with a dot in assets/dotclear and the link shoud be turned into an  tag.

So we miss the introductions to the entries and the images are treated as links. Can any of these points be fixed programmatically?

**Comment by jrfern** [comment]
Great! The excerpt was the only problem with the import, the issue with the images was a problem with the backup, not the import.

From my side the new code works and I have recuperated the posts from this old blog.

File: docs/_importers/dotclear.md [hunk 6]
```diff
@@ -4,3 +4,21 @@ prev_section: csv
...
+* Paths are always resolved relative to current directory.
+* Posts will be imported into `_drafts` directory to avoid overwriting any existing file with same filename inside `_posts`.
+* Posts will be imported as HTML files with `.html` file extension.
+* Excerpts if non-empty will be prepended onto content string separated by a blank line i.e. `<excerpt>\n\n<content>`.
+* The same excerpt will be added to front matter to prevent Jekyll from generating a separate excerpt.
+* Existing comments linked to posts in the export-file WILL NOT be imported.
+* "Categories" are not currently imported from the export-file.
+* "Tags" however will be imported and added to relevant posts' front matter.
+* Post URLs are imported from the export-file into front matter with key `original_url`.
+* Jekyll doesn't manage timezone for individual posts. Therefore, timezone metadata of individual posts will be ignored.
```
Comment (parkr) [inline docs/_importers/dotclear.md:19]: If a timezone offset is present, it would be preferable to preserve it for each post, I think. I always use timezone offsets in my post dates. If it's too hard to extract then we can skip it.

File: lib/jekyll-import/importers/dotclear.rb [hunk 7]
```diff
@@ -1,125 +1,182 @@
...
-            rubygems
-            fileutils
-            safe_yaml
-            date
-            active_support
-            active_support/core_ext/string/inflections
-            csv
-            pp
-          ))
+          JekyllImport.require_with_fallback(%w())
```
Comment (parkr) [inline lib/jekyll-import/importers/dotclear.rb:13]: Omit this if we don't require anything.

**Review by parkr — APPROVED** [review]

File: docs/_importers/dotclear.md (hunk 6 above)
Comment (ashmaroli) [reply docs/_importers/dotclear.md:19]: I agree with this. Unfortunately, the timezone here is the IANA id (e.g. `Europe/Madrid`) instead of the offset.
In the attached mock export-file, it is `"CET"`.

File: lib/jekyll-import/importers/dotclear.rb (hunk 7 above)
Comment (ashmaroli) [reply lib/jekyll-import/importers/dotclear.rb:13]: This is required for compatibility with the local plugin `docs/_plugins/importer_metadata.rb`.

**Comment by ashmaroli** [comment]
@jekyllbot: merge +minor

**Comment by ashmaroli** [comment]
@jekyllbot: merge +minor

**Comment by ashmaroli** [comment]
@jekyllbot: merge +minor
