### PR TITLE
(Tumblr) Add nil check to prevent undefined method error (fixes #29)

### LINKED ISSUE #29: Tumblr import fails `post_to_hash': undefined method `<<'…
I cannot import my blog. Doing:

```
$ ruby -rubygems -e 'require "jekyll/jekyll-import/tumblr";
>      JekyllImport::Tumblr.process("http://blog.julieng.me", "md", true)'
```
I get the following error message:
```
/Users/julieng/.rvm/gems/ruby-1.9.3-p194/gems/jekyll-import-0.1.0.beta1/lib/jekyll/jekyll-import/tumblr.rb:94:in `post_to_hash': undefined method `<<' for nil:NilClass (NoMethodError)
	from /Users/julieng/.rvm/gems/ruby-1.9.3-p194/gems/jekyll-import-0.1.0.beta1/lib/jekyll/jekyll-import/tumblr.rb:27:in `block in process'
	from /Users/julieng/.rvm/gems/ruby-1.9.3-p194/gems/jekyll-import-0.1.0.beta1/lib/jekyll/jekyll-import/tumblr.rb:27:in `map'
	from /Users/julieng/.rvm/gems/ruby-1.9.3-p194/gems/jekyll-import-0.1.0.beta1/lib/jekyll/jekyll-import/tumblr.rb:27:in `process'
	from -e:2:in `<main>'
```

It command works successfully for _other_ tumblrs, just not mine. Any ideas?

As far as I can tell, __I do not have any of the following which may be _problem_ post types__ (per google results and other issues):
* audio
* chats

I have the following post types:

* text
* photos
* videos
* links
* quotes
* reblogs
* "ask me anything" posts

Any ideas? Thanks for your help.

### PR DESCRIPTION
**Pull request by paramaggarwal**
Fix for this error when importing a Tumblr blog with video posts with empty `video-player` field:

```
Fetching http://paramaggarwal.com/api/read/json/?num=50&start=0
Page: 1 - Posts: 50
/usr/local/lib/ruby/gems/2.2.0/gems/jekyll-import-0.5.3/lib/jekyll-import/importers/tumblr.rb:136:in `post_to_hash': undefined method `<<' for false:FalseClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-import-0.5.3/lib/jekyll-import/importers/tumblr.rb:47:in `block in process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-import-0.5.3/lib/jekyll-import/importers/tumblr.rb:47:in `map'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-import-0.5.3/lib/jekyll-import/importers/tumblr.rb:47:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-import-0.5.3/lib/jekyll-import/importer.rb:23:in `run'
	from -e:2:in `<main>'
```

### CODE REVIEW

**Comment by parkr** [comment]
I don't think this will fix the error you got. You got an error because `content` was `false`.

**Comment by paramaggarwal** [comment]
Yes, you are right! I ran the importer after this change and it worked so I thought this fixed it. Now I'm confused.

File: lib/jekyll-import/importers/tumblr.rb [hunk 1]
```diff
@@ -131,8 +131,10 @@ def self.post_to_hash(post, format)
           when "video"
             title = post["video-title"]
             content = post["video-player"]
```
Comment (parkr) [inline lib/jekyll-import/importers/tumblr.rb]: If `content` is false, then it means something went wrong here.

**Comment by parkr** [comment]
> it worked so I thought this fixed it.

It could have been that it *also* had no `video-caption`, so it never called `#<<` on `content`.

**Comment by octalmage** [comment]
This fixed the errors I was getting:

```
/Users/jasonstallings/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/gems/jekyll-import-0.6.0/lib/jekyll-import/importers/tumblr.rb:135:in `post_to_hash': undefined method `<<' for false:FalseClass (NoMethodError)
        from /Users/jasonstallings/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/gems/jekyll-import-0.6.0/lib/jekyll-import/importers/tumblr.rb:47:in `block in process'
        from /Users/jasonstallings/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/gems/jekyll-import-0.6.0/lib/jekyll-import/importers/tumblr.rb:47:in `map'
        from /Users/jasonstallings/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/gems/jekyll-import-0.6.0/lib/jekyll-import/importers/tumblr.rb:47:in `process'
        from /Users/jasonstallings/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/gems/jekyll-import-0.6.0/lib/jekyll-import/importer.rb:23:in `run'
        from -e:2:in `<main>'
```

Import process worked without error with this change.

File: lib/jekyll-import/importers/tumblr.rb [hunk 2]
```diff
@@ -131,8 +131,10 @@ def self.post_to_hash(post, format)
...
-            unless post["video-caption"].nil?
-              content << "<br/>" + post["video-caption"]
+            unless post[:content].nil?
```
Comment (parkr) [inline lib/jekyll-import/importers/tumblr.rb]: Shouldn't this check `content`?

 ```ruby
unless content.nil? || post["video-caption"].nil?
  content << "<br/>" + post["video-caption"]
end
```

Comment (paramaggarwal) [inline lib/jekyll-import/importers/tumblr.rb]: Would you like me to make this change to the PR? Unfortunately, I would have no way to try it out though...

Comment (parkr) [inline lib/jekyll-import/importers/tumblr.rb]: Yes please! :)

**Comment by paramaggarwal** [comment]
@parkr Updated the PR with your review comments. Sorry for the immense delay for making this change...

File: lib/jekyll-import/importers/tumblr.rb [hunk 3]
```diff
@@ -131,7 +131,7 @@ def self.post_to_hash(post, format)
           when "video"
             title = post["video-title"]
             content = post["video-player"]
-            unless post["video-caption"].nil?
+            unless content.nil? || post["video-caption"].nil?
               content << "<br/>" + post["video-caption"]
             end
```
Comment (parkr) [inline lib/jekyll-import/importers/tumblr.rb]: if `content` is `nil`, should we say `content = post["video-caption"]`?

**Comment by paramaggarwal** [comment]
@parkr Makes sense! Updated PR.

**Comment by parkr** [comment]
:tada:
